module.exports = {
    DATA_NOT_INFORMED: 'DATA_NOT_INFORMED',
    DATA_EXISTS: 'DATA_EXISTS',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    DATA_DELETED: 'DATA_DELETED',
    DATA_CONFLICT: 'DATA_CONFLICT',
    DATA_INVALID: 'DATA_INVALID',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    RECORD_SUCCESS: 'RECORD_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    BAD_REQUEST: 'BAD_REQUEST'
}